module "tests"
{
    int testIf(int a, int b, bool condition)
    {
        if(condition)
            return a;
        return b;
    }

    int testIfElse(int a, int b, bool condition)
    {
        if(condition)
            return a;
        else
            return b;
        return 0;
    }

    int testWhile(int a, int b)
    {
        while(a < b)
        {
            a = a + 1;
        }
        return a;
    }
}