module "tests"
{
    int globalInt;
    float globalFloat;
    struct GlobalStruct
    {
        int var;
    }
    GlobalStruct globalStruct;

    void setInt(int v)
    {
        globalInt = v;
    }
    void setFloat(float v)
    {
        globalFloat = v;
    }
    void setStructVar(int v)
    {
        globalStruct.var = v;
    }
    int getInt()
    {
        return globalInt;
    }
    float getFloat()
    {
        return globalFloat;
    }
    int getStructVar()
    {
        return globalStruct.var;
    }
}