module "tests"
link "vector"
link "string"
{
    Vector<int> returnSimpleVector()
    {
        Vector<int> v;
        v.append(1);
        v.append(2);
        v.append(3);
        return v;
    }

    Vector<string> returnComplexVector()
    {
        Vector<string> v;
        v.append("a");
        v.append("b");
        v.append("c");
        v.append("d");
        return v;
    }

    string getIndex(ref Vector<string> v, int index)
    {
        return v[index];
    }

    void setIndex(ref Vector<string> v, int index, ref string value)
    {
        v[index] = value;
    }

    void clearVector(ref Vector<string> v)
    {
        v.clear();
    }
}