/* This file was auto generated, please use generateIncludesFile.py
 * to make changes, as the ones here may be overwritten */

export as "BraneScript" 
 {
    struct string{}
 
	bool opr ==(const ref string left, const ref string right) ext;
	bool opr !=(const ref string left, const ref string right) ext;
	char opr [](const ref string source, int index) ext;
	string opr +(const ref string left, const ref string right) ext;
}